site_name: Airquality Capstone Project
repo_url: https://github.com/SergeiOssokine/airquality_capstone
nav:
  - "Home": index.md
  - 'User Guide':
    - User Guide: "user_guide/user_guide.md"
    - Preparing location data in detail: "user_guide/location_data_deployment.md"
    - Performing analysis in detail: "user_guide/analysis_deployment.md"
  - 'Python API':
    - Module documentation: "python_docs/modules_api.md"

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.magiclink

theme:
  name: material
  palette:

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode


plugins:
- mkdocstrings:
    handlers:
      python:
        paths:  [.]
        options:
          docstring_style: google