version: 2

sources:
  - name: staging
    database: "{{ target.project }}"
    schema:
      "{{ target.schema }}"
    tables:
      - name:
          places
      - name:
          sensors
      - name:
          sensors_data